config/routes.rb
Rails.application.routes.draw do
  # Home
  get 'home', to: 'posts#home'
  # Root
  root 'posts#home'

  # Admin
  scope 'admin' do
    # Admin/Users
    resources :users do
      member do
        get 'change_password', to: 'users#edit_change_password', as: 'edit_change_password'
        patch 'change_password', to: 'users#change_password', as: 'change_password'
      end
    end
    # Admin/Posts
    resources :posts, except: [:show] do
      member do
        delete :delete_image_attachment
      end
      # Admin/Posts/PostAttributes
      resources :post_attributes, except: [:show]
    end
    # Admin/Categories
    resources :categories, except: [:show]
    # Admin/Messages
    resources :messages do
      collection do
        #Admin/Messages/Inbox
        get :inbox
      end
    end
  end

  # Posts
  resources :posts, only: [:show], as: 'rmpost' do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  # get 'p/:id', to: 'posts#visit_post', as: 'visit_post'
  
  # Categories
  resources :categories, only: [:show], as: 'show_category'
  # get 'c/:id', to: 'categories#show', as: 'show_category'

  # Sessions
  get 'admin', to: 'sessions#new'
  post 'admin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Policies
  get 'privacy', to: 'policies#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_secure_password

  validates :username, :first_name, :last_name, presence: true, length: {minimum: 2, maximum: 20}
  validates :username, uniqueness: {message: "already taken"}
  validates :password_confirmation, presence: true, if: -> {!password.nil?}
  validates :password, length: {minimum: 8, allow_nil: false}, if: -> {!password.nil?}
  validates :role, presence: true

  before_save :capitalize_fields
  # before_save :downcase_fields
  before_save :downcase_and_replace_space

  def capitalize_fields
    self.first_name = first_name.split.each { |n| 
      n.capitalize! 
    }.join(' ')
    self.last_name = last_name.split.each { |n| 
      n.capitalize! 
    }.join(' ')
  end

  # def downcase_fields
  #   self.username.downcase!
  # end

  def downcase_and_replace_space
    self.username = username.split.each { |n|
      n.downcase!
    }.join('_')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  before_action :set_user, only: [:show, :edit, :update, :edit_change_password, :change_password, :destroy]
  before_action :check_user, only: [:show, :edit, :update, :edit_change_password, :change_password]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, flash: { success: 'User was successfully created.' } }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, flash: { success: 'User was successfully updated.' } }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_change_password
  end

  def change_password
    user = User.find_by_username(current_user.username).try(:authenticate, params[:current_password])

    if user && @user.update(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to users_path
    else
      flash[:danger] = 'Invalid old password' unless user
      flash[:danger] = nil if user
      render 'edit_change_password'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, flash: { info: 'User was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <% unless user.id? %>
    <div class="form-group">
      <%= form.label 'Password' %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label 'Confirm password' %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-group">
      <div><%= form.label :role %></div>
      <%= form.select(:role, options_for_select([['Please select', ''], 
                                                ['Admin', 'admin'], 
                                                ['Editor', 'editor']]), {}, {class: 'btn btn-default dropdown-toggle'})  %>
    </div>
  <% end %>

  <div class="panel-footer">
    <div class="form-group text-center">
      <%= form.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', users_url %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/errors', obj: @user %>
    <%= render 'shared/flash' if flash_list %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Editing User</h1>
      </div>
      <div class="panel-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_change_password.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/errors', obj: @user %>
    <%= render 'shared/flash' if flash_list %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Change password</h1>
      </div>
      <div class="panel-body">
        <%= form_for(@user, url: {action: 'change_password'}) do |form| %>
          <div class="form-group">
            <%= form.label 'Old password'%>
            <%= password_field_tag :current_password, params[:current_password], class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label 'New password' %>
            <%= form.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label 'Confirm password' %>
            <%= form.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="panel-footer">
            <div class="form-group text-center">
              <%= form.submit class: "btn btn-success" %>
            </div>
          </div>
        <% end %>

        <%= link_to 'Back', users_url %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/flash' if flash_list %>

<div class="panel panel-default">
  <div class="panel-body">
    <h1>Users</h1>

    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Username</th>
            <th>Role</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.username %></td>
              <td><%= user.role %></td>
              <td><%= user.created_at %></td>
              <td><%= user.updated_at unless user.created_at == user.updated_at %></td>
              <% if user == current_user %>
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Edit', edit_user_url(user) %></td>
                <td><%= link_to 'Change Password', edit_change_password_user_url(user) %></td>
              <% else %>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <%= link_to 'New User', new_user_url %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/errors', obj: @user %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New User</h1>
      </div>
      <div class="panel-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/flash' if flash_list %>

<div class="panel panel-default">
  <div class="panel-body">
    <div>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </div>

    <div>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </div>

    <div>
      <strong>Username:</strong>
      <%= @user.username %>
    </div>

    <div>
      <strong>Password digest:</strong>
      <%= @user.password_digest %>
    </div>

    <div>
      <strong>Role:</strong>
      <%= @user.role %>
    </div>

    <%= link_to 'Edit', edit_user_url(@user) %> | 
    <%= link_to 'Change Password', edit_change_password_user_url(@user) %> |
    <%= link_to 'Back', users_url %>
  </div>
</div>