config/routes.rb
Rails.application.routes.draw do
  # Home
  get 'home', to: 'posts#home'
  # Root
  root 'posts#home'

  # Admin
  scope 'admin' do
    # Admin/Users
    resources :users do
      member do
        get 'change_password', to: 'users#edit_change_password', as: 'edit_change_password'
        patch 'change_password', to: 'users#change_password', as: 'change_password'
      end
    end
    # Admin/Posts
    resources :posts, except: [:show] do
      member do
        delete :delete_image_attachment
      end
      # Admin/Posts/PostAttributes
      resources :post_attributes, except: [:show]
    end
    # Admin/Categories
    resources :categories, except: [:show]
    # Admin/Messages
    resources :messages do
      collection do
        #Admin/Messages/Inbox
        get :inbox
      end
    end
  end

  # Posts
  resources :posts, only: [:show], as: 'rmpost' do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  # get 'p/:id', to: 'posts#visit_post', as: 'visit_post'
  
  # Categories
  resources :categories, only: [:show], as: 'show_category'
  # get 'c/:id', to: 'categories#show', as: 'show_category'

  # Sessions
  get 'admin', to: 'sessions#new'
  post 'admin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Policies
  get 'privacy', to: 'policies#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_category.html.erb
  <div class="btn-group btn-group-justified" role="group" aria-label="...">
    <% categories.each_with_index do |category, i|%>
      <% if i == 0 || i == 1 %>
        <div class="btn-group" role="group">
          <a href="<%= show_category_url(category) %>" class="btn btn-primary"><strong><%= category.category_name %></strong></a>
        </div>
      <% end %>
    <% end %>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <strong>More</strong>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% categories.each do |category|%>
          <li><%= link_to category.category_name, show_category_url(category) %></li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="panel panel-warning">
    <div class="panel-heading">
      <div class="panel-title">
        <h4>
          <%= pluralize(obj.errors.count, "error") %>
          prohibited form from being submitted:
        </h4>
      </div>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %> alert-dismissible fade in' role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if name == "danger" %>
      <i class="glyphicon glyphicon-remove"></i><strong><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></strong>
    <% else %>
      <i class="glyphicon glyphicon-ok"></i><strong><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></strong>
    <% end %>
  </div>
<% end %>

app/views/shared/_post_small_thumbnail.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-sm-6 col-md-4">
      <div class="media">
        <div class="media-left media-middle">
          <%= link_to(rmpost_url(post)) do %>
            <% if post.image.present? %>
              <%= image_tag post.image_url, class: "media-object" if post.image_url %>
            <% end %>
          <% end %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><span><%= link_to post.title, rmpost_url(post) %></span></h4>
          <div><span><%= post.description %></span></div>
          <div>
          <% post.post_attributes.first(2).each do |attribute| %>
            <div>
              <span><%= attribute.attribute_name %>: <strong><%= attribute.attribute_value %></strong></span>
            </div>
          <% end %>
          <% if current_user %>
            <%= link_to 'Edit', edit_post_url(post) %> | 
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_search.html.erb
<div class="search-bar">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <div class="search-bar-title text-center">
        <h2>YOU'RE ONE SEARCH AWAY FROM YOUR DREAM</h2>
      </div>
      <%= search_form_for @q, url: search_rmpost_index_url, 
                              html: {method: :post, 
                              class: "input-group input-group-lg"} do |form| %>
        <%= form.search_field :title_or_description_or_post_attributes_attribute_name_or_post_attributes_attribute_value_or_categories_category_name_cont, 
                              class: "form-control", 
                              placeholder: "Search for name, location or price..." %>
        <span class="input-group-btn">
          <%= form.button "Go!", class: "btn btn-primary", type: "submit" %>
        </span>
      <% end %>
    </div>
  </div>
</div>