config/routes.rb
Rails.application.routes.draw do
  # Home
  get 'home', to: 'posts#home'
  # Root
  root 'posts#home'

  # Admin
  scope 'admin' do
    # Admin/Users
    resources :users do
      member do
        get 'change_password', to: 'users#edit_change_password', as: 'edit_change_password'
        patch 'change_password', to: 'users#change_password', as: 'change_password'
      end
    end
    # Admin/Posts
    resources :posts, except: [:show] do
      member do
        delete :delete_image_attachment
      end
      # Admin/Posts/PostAttributes
      resources :post_attributes, except: [:show]
    end
    # Admin/Categories
    resources :categories, except: [:show]
    # Admin/Messages
    resources :messages do
      collection do
        #Admin/Messages/Inbox
        get :inbox
      end
    end
  end

  # Posts
  resources :posts, only: [:show], as: 'rmpost' do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  # get 'p/:id', to: 'posts#visit_post', as: 'visit_post'
  
  # Categories
  resources :categories, only: [:show], as: 'show_category'
  # get 'c/:id', to: 'categories#show', as: 'show_category'

  # Sessions
  get 'admin', to: 'sessions#new'
  post 'admin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Policies
  get 'privacy', to: 'policies#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  include ImageUploader::Attachment.new(:image)
  
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :post_attributes, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_one_attached :title_image
  has_many_attached :post_images

  scope :order_descending, -> { order(created_at: :desc) }

  validates :title, :image, :post_images, :description, :google_map_embed, presence: true
  validates :title, length: {minimum: 5, maximum: 50}
  validates :google_map_embed, length: {minimum: 130, maximum: 500}
  validates :description, length: {minimum: 50, maximum: 5000}
  # validates :title_image, attached: true, 
  #                         content_type: {in: [
  #                                               'image/png', 
  #                                               'image/jpg', 
  #                                               'image/jpeg'
  #                                             ], message: 'must be JPEG or PNG'} 
  #                         # dimension: { width: { min: 800, max: 2400 },
  #                         #             height: { min: 600, max: 1800 }, 
  #                         #             message: 'is not given between landscape dimension' }
  validates :post_images, content_type: {in: [
                                                'image/png', 
                                                'image/jpg', 
                                                'image/jpeg'
                                              ], message: 'must be JPEG or PNG'}
                          # dimension: { width: { min: 800, max: 2400 },
                          #             height: { min: 600, max: 1800 }, 
                          #             message: 'is not given between landscape dimension' }

  before_save :capitalize_fields

  private
    def capitalize_fields
      self.title = title.split.each { |w|
                      w.capitalize!
                    }.join(' ')
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: [:index, :new, :edit, :create, :update, :destroy, :delete_image_attachment]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :set_host_for_local_storage

  # GET /home
  def home
    @home = true
    @posts = Post.order_descending
    @carousel = Post.order_descending.first(3)
    @q = Post.order_descending.ransack(params[:q])
    @posts = @q.result(distinct: true)
    @render_category = true
  end

  # GET /search
  def search
    @search = true
    @render_category = true
    index
    render :index
  end

  # GET /posts
  # GET /posts.json
  def index
    @index = true
    @q = Post.order_descending.ransack(params[:q])
    @posts = @q.result(distinct: true)
    @render_category = true
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @render_category = true
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to new_post_post_attribute_path(post_id: @post.id), flash: { success: 'Post was successfully created.' } }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to rmpost_path(@post), flash: { success: 'Post was successfully updated.' } }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, flash: { info: 'Post was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    flash[:info] = 'Image was successfully removed.'
    redirect_back(fallback_location: posts_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :google_map_embed, :image, post_images: [], category_ids: [])
    end

    # For ActiveStorage service_url
    # def set_host_for_local_storage
    #   ActiveStorage::Current.host = request.base_url if Rails.application.config.active_storage.service == :local
    # end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_fb_share.html.erb
<!-- <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" 
        class="btn btn-fb" 
        title="Share on Facebook" 
        target="_blank"><#%= fa_icon('facebook', text: 'SHARE') %></a> -->

<iframe src="https://www.facebook.com/plugins/like.php?href=<%= request.original_url %>&width=154&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId=610478122777500" 
        width="154" 
        height="46" 
        style="border:none;overflow:hidden" 
        scrolling="no" 
        frameborder="0" 
        allowTransparency="true" 
        allow="encrypted-media"></iframe>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: '6' %>
  </div>

  <div class="form-group">
    <%= form.label :google_map_embed %>
    <%= form.text_area :google_map_embed, class: 'form-control', rows: '6' %>
  </div>

  <!-- <div class="form-group">
    <#%= form.label :title_image %>
    <#%= form.file_field :title_image, direct_upload: true %>
    <#%= link_to post.title_image.filename, 
                  post.title_image, 
                  target: :_blank if post.title_image.attached? %>
  </div> -->

  <div class="form-group">
    <%= form.label :thumbnail_image %>
    <%= form.hidden_field :image, 
                          value: post.cached_image_data %>
    <%= form.file_field :image,
                        accept: ImageUploader::ALLOWED_TYPES.join(',') %>
    <%= link_to post.image.original_filename, 
                  post.image_url, 
                  target: :_blank if post.image.present? %>
  </div>

  <div class="form-group">
    <%= form.label :post_images %>
    <%= form.file_field :post_images, multiple: true, direct_upload: true %>
    <% if post.post_images.attached? %>
      <ul>
      <% post.post_images.each do |image| %>
          <li>
            <%= link_to image.filename, image, target: :_blank %> | 
            <%= link_to 'Remove', delete_image_attachment_post_url(image),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } if image.id %>
          </li>
      <% end %>
      </ul>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <% if categories.any? %>
      <ul>
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :category_name do |cb| %>
          <li><%= cb.label(class: "") {cb.check_box(class: "") + cb.text} %></li>
        <% end %>
      </ul>
    <% else %>
      <div>No category found. Click <%= link_to 'here', new_category_url %> to add.</div> 
    <% end %>
  </div>

  <% if post.id? %>
    <div class="form-group">
      <%= form.label 'Post sub-attributes' %>
      <% if post.post_attributes.any? %>
        <ul>
          <% post.post_attributes.each do |post_attribute| %>
            <li>
              <%= "#{post_attribute.attribute_name}: #{post_attribute.attribute_value}" %>
              <%= link_to 'Edit', edit_post_post_attribute_url(post_id: post, id: post_attribute) %> | 
              <%= link_to 'Delete', post_post_attribute_url(post_id: post, id: post_attribute), 
                                    method: 'delete',
                                    data: {confirm: 'Are you sure?'} %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <div>No post attribute yet</div>
      <% end %>
      <div><%= link_to 'New post attribute', new_post_post_attribute_url(post_id: post.id) %></div>
    </div>
  <% end %>
  <div class="panel-footer">
    <div class="form-group text-center">
      <%= form.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', posts_url %>

app/views/posts/_post_read_more_modal.html.erb
<!-- Modal -->
<div id="postReadMoreModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2 class="modal-title"><%= post.title %></h2>
      </div>
      <div class="modal-body">
        <p><%= simple_format(post.description) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/errors', obj: @post %>
    <%= render 'shared/flash' if flash_list %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Editing Post</h1>
      </div>
      <div class="panel-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/home.html.erb
<% content_for :title, 'RM Real Estate Services - Home' %>
<div class="row">
  <% unless @posts.blank? %>
    <% @posts.each do |post| %>
      <div class="col-sm-6 col-md-4">
        <%= link_to (rmpost_url(post)) do %>
          <div class="thumbnail mod-thumbnail">
            <div class="category-tag">
              <% post.categories.first(2).each do |category| %>
                <div class="label label-danger category-tag-name">
                  <%= category.category_name %>
                </div>
              <% end %>
            </div>

            <% if post.image.present? %>
              <%= image_tag post.image_url if post.image_url %>
            <% end %>

            <div class="caption">
              <% post.post_attributes.first(2).each do |attribute| %>
                <div class="post-attribute">
                  <%= attribute.attribute_name %>:<strong> <%= attribute.attribute_value %></strong>
                </div>
              <% end %>

              <h3><%= post.title %></h3>
              <p><%= truncate(post.description, length: 100, omission: "... See More") %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="text-center">No post found</div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'shared/flash' if flash_list %>

<% unless params[:q].blank? && !@Search %>
  <% params[:q].each do |k,v| %>
    <h3>Search result for: <em><strong><%= v.blank? ? "_blank" : v  %></strong></em></h3>
  <% end %>
<% end %>

<% unless @posts.blank? %>
  <%= render 'shared/post_small_thumbnail', posts: @posts %>
<% else %>
  <div class="text-center">No post found</div>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/errors', obj: @post %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Post</h1>
      </div>
      <div class="panel-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>
<% content_for :description, truncate(@post.description, length: 150) %>
<% content_for :image, @post.image_url %>
<%= render 'shared/flash' if flash_list %>
<%= render 'posts/post_read_more_modal', post: @post %>

<div class="row">
  <div class="col-xs-12" id="slider">
    <!-- Top part of the slider -->
    <div class="row">
      <div class="col-sm-4">
        <div>
          <h2><%= @post.title %></h2>
          
          <div class="post-date">
            <em><%= @post.created_at.strftime('Posted on: %b %d, %Y') %></em>
          </div>

          <% @post.categories.each do |category| %>
            <div class="label label-danger category-tag-name">
              <%= category.category_name %>
            </div>
          <% end %>

          <div class="post-attribute-container">
            <% @post.post_attributes.each do |attribute| %>
              <div class="post-attribute">
                <%= attribute.attribute_name %>:<strong> <%= attribute.attribute_value %></strong>
              </div>
            <% end %>
          </div>

          <%= render 'posts/fb_share' %>
        </div>
      </div>

      <div class="col-sm-8">
        <!-- Slider -->
        <div class="slider">
          <ul id="lightSlider">
            <% @post.post_images.each do |image| %>
              <li data-thumb="<%= url_for(image) %>">
                <%= link_to image_tag(image), image, target: :_blank %>
              </li>
            <% end %>
          </ul>
        </div>
        <!--/Slider-->
      </div>
    </div>

    <div class="panel panel-default post-description">
      <div class="panel-body">
        <h2>Description</h2>
        <p>
          <%= simple_format(truncate(@post.description, length: 500)) %>
          <%= link_to 'Read More', '#postReadMoreModal', class: 'read-more-link', data: {toggle: 'modal'} if @post.description.length > 500 %>
        </p>
      </div>
    </div>
  </div>
</div>

<div id="map" class="map">
  <post 
    v-bind:post="post"
    v-for="post in currentPost(<%= @post.id %>)"/>
  <!-- <#%= raw(@post.google_map_embed) %> -->
</div>