config/routes.rb
Rails.application.routes.draw do
  # Home
  get 'home', to: 'posts#home'
  # Root
  root 'posts#home'

  # Admin
  scope 'admin' do
    # Admin/Users
    resources :users do
      member do
        get 'change_password', to: 'users#edit_change_password', as: 'edit_change_password'
        patch 'change_password', to: 'users#change_password', as: 'change_password'
      end
    end
    # Admin/Posts
    resources :posts, except: [:show] do
      member do
        delete :delete_image_attachment
      end
      # Admin/Posts/PostAttributes
      resources :post_attributes, except: [:show]
    end
    # Admin/Categories
    resources :categories, except: [:show]
    # Admin/Messages
    resources :messages do
      collection do
        #Admin/Messages/Inbox
        get :inbox
      end
    end
  end

  # Posts
  resources :posts, only: [:show], as: 'rmpost' do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  # get 'p/:id', to: 'posts#visit_post', as: 'visit_post'
  
  # Categories
  resources :categories, only: [:show], as: 'show_category'
  # get 'c/:id', to: 'categories#show', as: 'show_category'

  # Sessions
  get 'admin', to: 'sessions#new'
  post 'admin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Policies
  get 'privacy', to: 'policies#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_banner.html.erb
<div class="banner">
  <div id="carousel" class="carousel slide mod-carousel" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @carousel.each_index do |i|%>
        <% if i == 0 %>
          <li data-target="#carousel" data-slide-to="<%= i %>" class="active"></li>
        <% else %>
          <li data-target="#carousel" data-slide-to="<%= i %>"></li>
        <% end %>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% @carousel.each_with_index do |post, i| %>
        <% if i == 0 %>
          <div class="item active mod-item" style="background-image: url(<%= url_for(post.image_url) %>);">
            <% if post.image.present? %>
              <%= image_tag post.image_url if post.image_url %>
            <% end %>
            <div class="carousel-caption">
              <h3><%= post.title %></h3>
              <p><%= truncate(post.description, length: 100) %></p>
              <p><%= link_to "Learn More", rmpost_url(post), class: "btn btn-default", role: "button" %></p>
            </div>
          </div>
        <% else %>
          <div class="item mod-item" style="background-image: url(<%= url_for(post.image_url) %>);">
            <% if post.image.present? %>
              <%= image_tag post.image_url if post.image_url %>
            <% end %>
            <div class="carousel-caption">
              <h3><%= post.title %></h3>
              <p><%= truncate(post.description, length: 100) %></p>
              <p><%= link_to "Learn More", rmpost_url(post), class: "btn btn-default", role: "button" %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#carousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/layouts/_contact_us_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="contactModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <form class=""
              v-on:submit.prevent="createMessage($event)">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title">Contact Us</h3>
        </div>

        <div class="row">
          <div class="contact text-center">
            <div class="col-lg-6 col-md-6">
              <div class="contact-details">
                <%= link_to "https://www.facebook.com/NegrosHomesAndcondominiums/", target: :_blank do %>
                  <div><%= fa_icon("facebook-square 2x") %></div>
                  <div><strong>Negros Homes And Condominiums</strong></div>
                <% end %>
              </div>
            </div>
            <div class="col-lg-6 col-md-6">
              <div class="contact-details">
                <div><%= fa_icon("phone-square 2x") %></div>
                <div><strong>Smart</strong> +63 949-466-4194</div>
                <div><strong>Globe</strong> +63 917-649-7656</div>
              </div>
            </div>
          </div>
        </div>

        <div class="panel panel-success">
          <div class="panel-heading">Your details are guaranteed safe</div>
          <div class="panel-body">
            <em>This website's database is secured with AES 256 encryption</em>
          </div>
        </div>

        <div class="modal-body">
          <div class="row">
            <div class="col-lg-6 col-md-6">
              <div class="form-group">
                <label>First name</label>
                <input class="form-control" 
                        type="text" 
                        name="first_name" 
                        required="true" 
                        minlength="2" 
                        maxlength="20" 
                        v-model="message.first_name">
              </div>
            </div>

            <div class="col-lg-6 col-md-6">
              <div class="form-group">
                <label>Last name</label>
                <input class="form-control" 
                        type="text" 
                        name="last_name" 
                        required="true" 
                        minlength="2" 
                        maxlength="20" 
                        v-model="message.last_name">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6">
              <div class="form-group">
                <label>Email</label>
                <input class="form-control" 
                        type="email" name="email" 
                        required="true" 
                        minlength="8" 
                        maxlength="40" 
                        v-model="message.email">
              </div>
            </div>

            <div class="col-lg-6 col-md-6">
              <div class="form-group">
                <label>Mobile number</label>
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">+63</span>
                  <input class="form-control" 
                          type="number" 
                          name="mobile_number" 
                          required="true" 
                          oninput="javascript: if (this.value.length > this.maxLength) 
                                                    this.value = this.value.slice(0, this.maxLength);"
                          maxlength = "10"
                          v-model="message.mobile_number">
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label>Enquiry</label>
            <textarea class="form-control" 
                      name="enquiry" 
                      required="true" 
                      minlength="10" 
                      maxlength="2000" 
                      rows="8" 
                      v-model="message.enquiry"></textarea>
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn btn-success">Send</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="text-center">
      <a href="#contactModal" data-toggle="modal">
      	CONTACT US <%= fa_icon("facebook-square") %> <%= fa_icon("phone-square") %>
      </a>
      | <%= link_to "Privacy Policy", privacy_url %>
    </div>
    <div class="text-center">
      Copyright &copy; <%= Time.now.year %> RM Real Estate Services
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
                            data-toggle="collapse" 
                            data-target="#bs-example-navbar-collapse-1" 
                            aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("https://s3.amazonaws.com/combite-real-estate/public/rmres-logo.png", 
                            alt: "RM Real Estate Services"), root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" 
                                              role="button" aria-haspopup="true" 
                                              aria-expanded="false"><strong>Categories</strong><span 
                                              class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if categories.any? %>
              <% categories.each do |category| %>
                <li><%= link_to category.category_name, show_category_url(category) %></li>
              <% end %>
            <% else %>
              <li><a href="">No category found</a></li>
            <% end %>
          </ul>
        </li>
        <!-- <li><#%= link_to "Contact us", root_url, class: "nav-bar-link" %></li> -->
        <li><a class="nav-bar-link" href="#contactModal" data-toggle="modal">Contact us</a></li>
        <li><%= link_to "About", root_url, class: "nav-bar-link" %></li>
        <% if current_user %>
          <li><a class="nav-bar-link" href="<%= inbox_messages_url %>">Inbox <span class="badge badge-warning" v-if="unreads.length > 0">{{ unreads.length }}</span></a></li>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown" 
                                                role="button" aria-haspopup="true" 
                                                aria-expanded="false"><strong>Actions</strong><span 
                                                class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Post", new_post_url %></li>
              <li><%= link_to "Manage Posts", posts_url %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Category", new_category_url %></li>
              <li><%= link_to "Manage Categories", categories_url %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Manage Users", users_url %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_url, method: "delete", class: "" %></li>
            </ul>
          </li>
          <li><a>Signed in as: <strong><%= current_user.username %></strong></a></li> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_property_specialists.html.erb
<div class="property-specialists">
  <div class="container">
    <h2 class="text-center">&#x2654; PROPERTY SPECIALISTS &#x2654;</h2>
    <div class="row text-center">
      <div class="col-md-6">
        <div class="property-specialists-content">
          <img src="https://combite-real-estate.s3.amazonaws.com/public/romeo.jpg" 
                alt="romeo combite"
                class="img-circle">
          <h3>Romeo Morante Combite</h3>
        </div>
      </div>
      <div class="col-md-6">
        <div class="property-specialists-content">
          <img src="https://combite-real-estate.s3.amazonaws.com/public/mechel.jpg" 
                alt="mechel combite"
                class="img-circle">
          <h3>Mechel Colaler Combite</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'RM Real Estate Services' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
    <%= javascript_pack_tag 'contact' %>
    <%= javascript_pack_tag 'inbox' %>
    <%= javascript_pack_tag 'api' %>
    <%= favicon_link_tag "https://s3.amazonaws.com/combite-real-estate/public/rmres-logo.png" %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="<%= yield(:description) %>">

    <!-- Facebook Open Graph -->
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%= yield(:title) %>">
    <meta property="og:description" content="<%= yield(:description) %>">
    <meta property="og:image" content="<%= content_for?(:image) ? yield(:image) : 'https://combite-real-estate.s3.amazonaws.com/public/rmres-logo-white-bg.jpg' %>">
    <meta property="og:app_id" content="610478122777500">
  </head>

  <body>
    <div id="contact">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/contact_us_modal' %>
    </div>
    
    <%= render 'layouts/banner' if @home && @carousel.count > 1 %>
    <%= render 'shared/search' if @home || @index %>
    <%= render 'shared/category' if @render_category %>

    <div class="container">
      <div class="main">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/property_specialists' if @home %>
    <%= render 'layouts/footer' %>
  </body>
</html>